#!/usr/bin/env bash

# this script starts conky on all available monitors in the same position

monitor_count=$(xrandr | grep ' conn' | wc -l)

conky
for (( i = 1; i < $monitor_count; i++ )); do
    conky -x "-$(( 1920 * $i - 52 ))"
done

# vim: ft=sh
